### ISSUE TITLE
Could not find module "@nativescript/schematics"

### ISSUE THREAD

**Issue by spiritguide7** [NativeScript/nativescript-schematics#130]
After issuing:
sudo yarn global add @nativescript/schematics

warning "@nativescript/schematics@0.3.3" has no binaries

'/Users/xxx/.npm-global/lib/node_modules'
total 0
0 drwxr-xr-x   6 root  staff   192B Oct 10 17:05 ./
0 drwxr-xr-x   3 root  staff    96B Oct 10 17:05 @angular-devkit/
0 drwxr-xr-x   3 root  staff    96B Oct 10 17:02 @nativescript/
0 drwxr-xr-x  27 root  staff   864B Oct 10 17:00 nativescript/
0 drwxr-xr-x   3 root  staff    96B Oct  7 14:44 @angular/

I then try to use  @nativescript/schematics:

ng new --collection=@nativescript/schematics --name=my-app

Could not find module   "@nativescript/schematics"  from "/Users/xxx/nscript".

Any suggestions why ng new doesn't recognize @nativescript/schematics?

It looks like ng new is looking in Users/xxx/.config/yarn/global/node_modules, but I don't see a @nativescript/schematics entry there.

Could not find module "@nativescript/schematics" from "/Users/jackhopkins/nscript".
Error: Could not find module "@nativescript/schematics" from "/Users/jackhopkins/nscript".
at Object.resolve (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/core/node/resolve.js:141:11)
at NodeModulesEngineHost._resolvePackageJson (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
at NodeModulesEngineHost._resolveCollectionPath (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
at NodeModulesEngineHost.createCollectionDescription (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:111:27)
at SchematicEngine._createCollectionDescription (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
at SchematicEngine.createCollection (/Users/jackhopkins/.config/yarn/global/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
at NewCommand.getCollection (/Users/jackhopkins/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:74:35)
at NewCommand.getOptions (/Users/jackhopkins/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:292:33)
at NewCommand. (/Users/jackhopkins/.config/yarn/global/node_modules/@angular/cli/commands/new-impl.js:37:49)
at Generator.next ()

**Comment by spiritguide7** [comment]
Update:
I uninstalled yarn.  That fixed the problem.

**Comment by isawk** [comment]
In my case, the following worked

`npm install --save-dev @schematics/angular`
`npm install --save-dev @nativescript/schematics`

**Comment by gyansoft786** [comment]
> In my case, the following worked
> 
> `npm install --save-dev @schematics/angular`
> `npm install --save-dev @nativescript/schematics`

thanks, it worked for  me

**Comment by andre505** [comment]
> In my case, the following worked
> 
> `npm install --save-dev @schematics/angular`
> `npm install --save-dev @nativescript/schematics`

Worked for me too! Thanks

**Comment by shankar722** [comment]
> In my case, the following worked
> 
> `npm install --save-dev @schematics/angular`
> `npm install --save-dev @nativescript/schematics`

Thanks, worked for me too!

**Comment by biswajitkar01** [comment]
In my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics

**Comment by punj** [comment]
In my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics

Thanks

**Comment by Almutlaqm** [comment]
In my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics

Thanks

**Comment by iiviioe** [comment]
In my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics

Thanks

**Comment by Chris-AM** [comment]
In my case it didn't work. I've tried many times installing the npm packages you shared before, but when i try to generate the component, it still show the exception

**Comment by rajasekhard2015** [comment]
my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics
