### ISSUE TITLE
App crashing right after start

### ISSUE THREAD

**Issue by JonasJW** [NativeScript/nativescript-schematics#143]
I created my app with this command: ng new --collection=@nativescript/schematics ProjectFit

After that I run `npm install`, then `tns run ios --bundle`. The app loads on my emulator and start. After showing the splashscreen for a few secounds it crashes. I don't get any errors in my console. The last message I got is 'Successfully synced application org.nativescript.ProjectFit on device C7A71CC6-7A76-47DE-B442-93463199840C.'

`ng serve` works just fine...

EDIT: I just tried installing the .apk on android. Here I atleast get an error:

`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5934)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:311)
	at com.tns.Runtime.run(Runtime.java:544)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5931)
	... 8 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:146)
	at com.tns.Module.bootstrapApp(Module.java:309)
	... 12 more`

**Comment by jfalmoguera** [comment]
I have exactly the same problem. 

In my case I have noticed that typescript files are not being transpiled, so I think this is because the error "No entry point file...."

**Comment by JonasJW** [comment]
Yep I have no Idea where this is coming from but there are other people with the same issue. Here is a stackoverflow post: https://stackoverflow.com/questions/53196685/nativescript-angular-code-sharing-project

**Comment by sebawita** [comment]
We are investigating the issue and hopefully will be able to provide a fix soon

**Comment by skopekreep** [comment]
Likely the same issue as [6552](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438046602).  Solution posted there.
