### ISSUE TITLE
Fail to build app with custom source dir

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-schematics#161]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: next
 - Cross-platform modules: next
 - Android Runtime: next
 - iOS Runtime: next
 - Plugin(s): No

**Describe the bug**
Apps created with custom src and prefix can not be build.

**To Reproduce**

Steps:
```
ng new --collection=@nativescript/schematics TestApp --prefix=myapp --sourceDir=mysrc --style=css
TestApp/node_modules/.bin/update-app-ng-deps
TestApp/node_modules/.bin/update-ns-webpack --deps --configs
tns run android --path TestApp --bundle
````
Result:
```
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-liveSync hook from /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-watchPatterns hook from /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/hooks/before-watchPatterns/nativescript-dev-typescript.js
Executing before-watchPatterns hook from /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/hooks/before-watch/nativescript-dev-typescript.js
Hook skipped because bundling is in progress.
Executing before-watch hook from /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/hooks/before-watch/nativescript-dev-webpack.js
Running webpack for Android...
/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: The specified path to app directory /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/app does not exist. Unable to find entry module.
    at verifyEntryModuleDirectory (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/nativescript-dev-webpack/index.js:79:9)
    at Object.exports.getEntryModule (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/nativescript-dev-webpack/index.js:30:2)
    at module.exports.env (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/webpack.config.js:54:38)
    at handleFunction (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/webpack-cli/bin/prepareOptions.js:23:13)
    at prepareOptions (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/webpack-cli/bin/convert-argv.js:136:14)
    at /Users/nsbuilduser/workspace/master-schematics-smoke-osx/TestApp/node_modules/webpack-cli/bin/convert-argv.js:142:17
```

**Expected behavior**
No errors when building an app.

**Comment by dtopuzov** [comment]
Looks to be not a valid issue.
I pass `--sourceDir=mysrc` and did not pass `--shared`.
Docs do not say I can pass `--sourceDir` on not shared project, so it looks not supported scenario.
