### ISSUE TITLE
tns generate service  fails 

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-schematics#188]
nativescript cli v 5.2.0

Steps:
ng new --collection=@nativescript/schematics my-mobile-app
tns generate service name=my-service

Fails with:
RangeError: Maximum call stack size exceeded
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at e._trySubscribe (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4751)
    at e.subscribe (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4427)
    at e.call (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1459)
    at e.subscribe (C:\Users\endarova\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4299)

**Comment by endarova** [comment]
#https://github.com/NativeScript/nativescript-cli/issues/4209

**Comment by sebawita** [comment]
Hi @endarova,

Can you try to use the Angular CLI instead?

```
ng generate service my-service
```
