### ISSUE TITLE
`ng generate library` doesn't work

### ISSUE THREAD

**Issue by xxyyzz2050** [NativeScript/nativescript-schematics#215]
when running the command `ng generate library myLibrary`, the following error occurs:

```
Schematic "library" not found in collection "@nativescript/schematics".
Error: Schematic "library" not found in collection "@nativescript/schematics".
    at SchematicEngine.createSchematic (D:\eldeebCMS\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:232:23)
    at CollectionImpl.createSchematic (D:\eldeebCMS\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at GenerateCommand.getSchematic (D:\eldeebCMS\node_modules\@angular\cli\models\schematic-command.js:137:27)
    at GenerateCommand.initialize (D:\eldeebCMS\node_modules\@angular\cli\models\schematic-command.js:45:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

it was working fine before setting up NativeScript

**Comment by MrCroft** [comment]
Generating/migrating libraries is really required in the Angular world.
Large apps or monorepos make heavy usage of libraries.
Right now, it involves some manual work:
1. Generate the library with `@angular/schematics` instead of `@nativescript/schematics`
2. Manually create all the **tns files** (because migration doesn't work either, it seems that the nativescript schematics doesn't work with anything outside the app folder, no matter how I've tried to "trick" it to take the path to the library's src/lib folder, where the NgModule is)
3. Edit the library's `tslint.json` to add `"prefer-mapped-imports": false` because the lib should use relative paths when importing from itself.
4. Manually add to the "paths" object in `tsconfig.tns.json`

And Step 2 is to be repeated each time we add a module or a component to the existing library.

For example:
1. `ng generate @schematics/angular:library @my-namespace/my-lib`
```console
CREATE projects/my-namespace/my-lib/karma.conf.js (1038 bytes)
CREATE projects/my-namespace/my-lib/ng-package.json (174 bytes)
CREATE projects/my-namespace/my-lib/package.json (152 bytes)
CREATE projects/my-namespace/my-lib/README.md (987 bytes)
CREATE projects/my-namespace/my-lib/tsconfig.lib.json (555 bytes)
CREATE projects/my-namespace/my-lib/tsconfig.spec.json (252 bytes)
CREATE projects/my-namespace/my-lib/tslint.json (250 bytes)
CREATE projects/my-namespace/my-lib/src/test.ts (670 bytes)
CREATE projects/my-namespace/my-lib/src/public-api.ts (155 bytes)
CREATE projects/my-namespace/my-lib/src/lib/my-lib.module.ts (222 bytes)        
CREATE projects/my-namespace/my-lib/src/lib/my-lib.component.spec.ts (622 bytes)
CREATE projects/my-namespace/my-lib/src/lib/my-lib.component.ts (255 bytes)     
CREATE projects/my-namespace/my-lib/src/lib/my-lib.service.spec.ts (329 bytes)  
CREATE projects/my-namespace/my-lib/src/lib/my-lib.service.ts (134 bytes)       
UPDATE angular.json (7513 bytes)
UPDATE package.json (2747 bytes)
UPDATE tsconfig.json (1198 bytes)
```

2. Manually add the following to `tsconfig.tns.json` paths:
```json
"@my-namespace/my-lib": [
  "projects/my-namespace/my-lib/src/public-api"
],
"@my-namespace/my-lib/*": [
  "projects/my-namespace/my-lib/src/lib/*"
]
```
Normally, the Angular CLI only adds paths for the built version of the library in the root tsconfig.json,  but we also add the above paths so we can work with the libraries without building them (also, really required while actually developing a lib):
```
"@my-namespace/my-lib": [
  "dist/my-namespace/my-lib", // << added by the CLI
  "projects/my-namespace/my-lib/src/public-api" // << manually added so we can work with the library without building it
],
"@my-namespace/my-lib/*": [
  "dist/my-namespace/my-lib/*", // << added by the CLI
  "projects/my-namespace/my-lib/src/lib/*" // << manually added so we can work with the library without building it
]
```

3. Edit the library's `tslint.json` to add `"prefer-mapped-imports": false` because the lib should use relative paths when importing from itself.

4. Manually create `projects/my-namespace/my-lib/src/lib/my-lib.module.tns.ts`
5. Futher, for creation of additional modules and/or components in a library, we still can't use nativescript schematics. This would be the project's structure:
```
/projects
    /my-namespace
        /my-lib-1
        /my-lib-2
    /my-app
```
Couldn't trick `@nativescript/schematics` to do anything outside the `my-app` folder.
Running `ng generate @nativescript/schematics:component my-component --project=@my-namespace/my-lib` generates the following error: `Failed to find generated component file /my-component.component.css. Please contact the @nativescript/schematics author.`
This must be because nativescript schematics doesn't look at the `projectType` property in angular.json, so it doesn't know it's a "library" and for a library the files are in `{newProjectRoot}/{project}/src/lib`
So, we have to manually create the tns files each time we add a module/component to a lib. Imagine a library that hosts tenths of shared components, each component also having it's own module.

Yet, the biggest headache I've had was until I've realized that nativescript schematics also adds the `paths` property to `tsconfig.app.json` (without nativescript schematics, the paths are only in the root `tsconfig.json` and generating a library only updates the paths there). But the paths from the root `tsconfig.json` are overwritten by the paths in `tsconfig.app.json`. And the IDE wasn't signaling any error when lazy loading the module like `loadChildren: () => import('@my-namespace/feature-auth/feature-auth.module').then(m => m.MyFeatureAuthModule)`, but ng serve/ng build was saying it can't find the module. And it was very confusing, because the IDE was fine with that import path.
