### ISSUE TITLE
feat: compatibility with @angular/cli@8.2

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-schematics#234]
**Describe the bug**
Migrate web to shared project do not work properly with @angular/cli@8.2.

**To Reproduce**
```
npm i nativescript@next -g
npm i @angular/cli@latest -g
npm i @nativescript/schematics@next -g
ng new TestApp --skip-install
npm i @nativescript/schematics@next --save-dev --save-exact
ng add @nativescript/schematics@next
ng serve -> OK
tns run android --path TestApp --emulator
```

App crash with:
```
Installing on device emulator-5562...
Successfully installed on device with identifier 'emulator-5562'.
Restarting application on device emulator-5562...
Successfully synced application org.nativescript.ngsample on device emulator-5562.
ActivityManager: Start proc 3377:org.nativescript.ngsample/u0a55 for activity org.nativescript.ngsample/com.tns.NativeScriptActivity
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.ngsample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Component AutoGeneratedComponent is not part of any NgModule or the module has not been imported into your module.
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ngsample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Component AutoGeneratedComponent is not part of any NgModule or the module has not been imported into your module.
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Component AutoGeneratedComponent is not part of any NgModule or the module has not been imported into your module.
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err: 	at android.app.Activity.performCreate(Activity.java:6237)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
System.err: 	... 9 more
```

**Expected behavior**
App works properly.

**Additional context**
It is ok with `@angular/cli@8.1`.

**Comment by vakrilov** [comment]
Looks like with `@angular/cli@8.2` the `component` schematic no longer registers the component in the module. The `AutoGeneratedComponent` is not added to the AppModule's directives.

Using the component schematic standalone alsoe fails to add the generated component to the given module (it works with `@angular/cli@8.1`):
```
ng g c auto-generated2 --module app 
```
