### ISSUE TITLE
An uncaught Exception occurred on "main" thread

### ISSUE THREAD

**Issue by thruthesky** [NativeScript/nativescript-schematics#250]
When I create a fresh code sharing app with command ng new -c=@nativescript/schematics ns6 --shared --style=scss, There is an error like below on tns run andriod.

Can somebody help me?

It is not working on iOS also.

But It's working without code sharing.

One thing to note is that: I installed Nativescript environment a year ago. And I just updated Nativescript and try to run.

I even installed @nativescript/schematics@0.3.0-rc.1 and it's still not working.

**Environment**
Provide the content of the `package.json` file in the project:
```
{
  "name": "ns6",
  "nativescript": {
    "id": "org.nativescript.ns6",
    "tns-android": {
      "version": "6.1.2"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android",
    "ios": "tns run ios",
    "mobile": "tns run",
    "preview": "tns preview"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "core-js": "^2.5.4",
    "nativescript-angular": "~8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular-devkit/build-angular": "~0.800.0",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.0.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "node-sass": "^4.7.1"
  }
}
```

**Describe the bug**
When I create a fresh code sharing app with command ng new -c=@nativescript/schematics ns6 --shared --style=scss, There is an error like below on tns run andriod.

Can somebody help me?

It is not working on iOS also.

But It's working without code sharing.

One thing to note is that: I installed Nativescript environment a year ago. And I just updated Nativescript and try to run.

I even installed @nativescript/schematics@0.3.0-rc.1 and it's still not working.

**To Reproduce**
$ ng new -c=@nativescript/schematics projectName --shared --style=scss
$ cd projectName
$ tns run android

**Expected behavior**

It should run on device.

**Sample project**
https://github.com/thruthesky/ns6

**Additional context**

```
ERROR in node_modules/@types/jasminewd2/index.d.ts(8,23): error TS2688: Cannot find type definition file for 'jasmine/v2'.

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.ns6/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ns6/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3115)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7073)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7327)
System.err:     at android.app.Activity.performCreate(Activity.java:7318)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
System.err:     ... 11 more
Successfully synced application org.nativescript.ns6 on device 320066b04746b53d.
```

**Comment by thruthesky** [comment]
It's working after removing `ERROR in node_modules/@types/jasminewd2/index.d.ts(8,23): error TS2688: Cannot find type definition file for 'jasmine/v2'.`.

I simply deleted the `/// <reference types="jasmine/v2" />` and it's working on both Android & iOS
